/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    areas: Area;
    faqs: Faq;
    testimonials: Testimonial;
    'gallery-items': GalleryItem;
    awards: Award;
    media: Media;
    'quote-requests': QuoteRequest;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    areas: AreasSelect<false> | AreasSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'gallery-items': GalleryItemsSelect<false> | GalleryItemsSelect<true>;
    awards: AwardsSelect<false> | AwardsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'quote-requests': QuoteRequestsSelect<false> | QuoteRequestsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    'quote-pricing': QuotePricing;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'quote-pricing': QuotePricingSelect<false> | QuotePricingSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  slug: string;
  title: string;
  /**
   * Optional thumbnail shown on this page’s dashboard card. Falls back to the first image in the page.
   */
  cardImage?: (number | null) | Media;
  heroHeading?: string | null;
  heroSub?: string | null;
  sections?:
    | (
        | RichTextBlock
        | ImageTextBlock
        | UseCaseTabsBlock
        | ProcessTimelineBlock
        | StatsCountersBlock
        | CtaBandBlock
        | FaqListBlock
        | TestimonialStripBlock
        | GalleryStripBlock
        | AwardBadgeBlock
      )[]
    | null;
  /**
   * Search-engine title tag and meta description for this page.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  heading?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageTextBlock".
 */
export interface ImageTextBlock {
  heading?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  imageSide?: ('left' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "UseCaseTabsBlock".
 */
export interface UseCaseTabsBlock {
  heading?: string | null;
  tabs?:
    | {
        label: string;
        heading: string;
        body: string;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'useCaseTabs';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProcessTimelineBlock".
 */
export interface ProcessTimelineBlock {
  heading?: string | null;
  /**
   * Every step renders in the home page Build Story. The animated build illustration is hand-tuned for exactly 5 steps — any other count still animates, but falls back to evenly-spaced scene sampling (scene beats no longer align 1:1 with each step).
   */
  steps?:
    | {
        title: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'processTimeline';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsCountersBlock".
 */
export interface StatsCountersBlock {
  heading?: string | null;
  stats?:
    | {
        value: number;
        /**
         * Rendered tight after the number — start word suffixes with a space, e.g. " weeks", " days", "-year".
         */
        suffix?: string | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'statsCounters';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBandBlock".
 */
export interface CtaBandBlock {
  heading: string;
  body?: string | null;
  buttonLabel?: string | null;
  buttonHref?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaBand';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqListBlock".
 */
export interface FaqListBlock {
  heading?: string | null;
  /**
   * Leave empty to show all FAQs in order.
   */
  faqs?: (number | Faq)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faqList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialStripBlock".
 */
export interface TestimonialStripBlock {
  heading?: string | null;
  /**
   * Leave empty to show featured testimonials.
   */
  testimonials?: (number | Testimonial)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonialStrip';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  author: string;
  platform: 'google' | 'yell' | 'facebook';
  /**
   * Short review headline, e.g. "What a team!"
   */
  title?: string | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryStripBlock".
 */
export interface GalleryStripBlock {
  heading?: string | null;
  /**
   * Optional filter — leave empty to use the picked items below.
   */
  category?: ('exterior' | 'interior' | 'build-progress' | 'before-after') | null;
  items?: (number | GalleryItem)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'galleryStrip';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-items".
 */
export interface GalleryItem {
  id: number;
  image: number | Media;
  alt: string;
  category: 'exterior' | 'interior' | 'build-progress' | 'before-after';
  /**
   * Optional — when set, the frontend renders a before/after slider.
   */
  beforeImage?: (number | null) | Media;
  caption?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AwardBadgeBlock".
 */
export interface AwardBadgeBlock {
  heading?: string | null;
  award?: (number | null) | Award;
  id?: string | null;
  blockName?: string | null;
  blockType: 'awardBadge';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards".
 */
export interface Award {
  id: number;
  title: string;
  /**
   * Awarding body, e.g. Northern Enterprise Awards.
   */
  body?: string | null;
  year?: number | null;
  image?: (number | null) | Media;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "areas".
 */
export interface Area {
  id: number;
  slug: string;
  name: string;
  region: 'north-west' | 'london';
  /**
   * Regional hub page (North West / London).
   */
  isHub?: boolean | null;
  heroHeading?: string | null;
  /**
   * The unique local copy for this area.
   */
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Local housing stock / planning context / landmarks.
   */
  localAngles?:
    | {
        heading: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Localised FAQs for this area.
   */
  faqs?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Search-engine title tag and meta description for this page.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quote-requests".
 */
export interface QuoteRequest {
  id: number;
  type: 'full' | 'instant' | 'assistant';
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  postcode: string;
  addressLine1?: string | null;
  town?: string | null;
  message?: string | null;
  /**
   * House style — access/complexity context; not a price input.
   */
  propertyType?: ('detached' | 'semi' | 'terraced' | 'bungalow' | 'flat') | null;
  timeline?: ('asap' | '1-3m' | '3-6m' | 'exploring') | null;
  /**
   * Free-text material preferences (e.g. brick, render, bi-folds).
   */
  materialPreferences?: string | null;
  /**
   * Estimator inputs and indicative range (instant wizard + assistant).
   */
  estimator?: {
    extensionType?: string | null;
    sizeBand?: string | null;
    areaM2?: number | null;
    widthM?: number | null;
    depthM?: number | null;
    spec?: string | null;
    estimateLow?: number | null;
    estimateHigh?: number | null;
    /**
     * Postcode is beyond the survey radius — a call-out fee applies.
     */
    surveyRequired?: boolean | null;
    /**
     * Survey call-out fee (£).
     */
    surveyFee?: number | null;
    /**
     * Straight-line miles from the HQ postcode.
     */
    distanceMiles?: number | null;
  };
  status: 'new' | 'contacted' | 'closed';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'areas';
        value: number | Area;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'gallery-items';
        value: number | GalleryItem;
      } | null)
    | ({
        relationTo: 'awards';
        value: number | Award;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'quote-requests';
        value: number | QuoteRequest;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  cardImage?: T;
  heroHeading?: T;
  heroSub?: T;
  sections?:
    | T
    | {
        richText?: T | RichTextBlockSelect<T>;
        imageText?: T | ImageTextBlockSelect<T>;
        useCaseTabs?: T | UseCaseTabsBlockSelect<T>;
        processTimeline?: T | ProcessTimelineBlockSelect<T>;
        statsCounters?: T | StatsCountersBlockSelect<T>;
        ctaBand?: T | CtaBandBlockSelect<T>;
        faqList?: T | FaqListBlockSelect<T>;
        testimonialStrip?: T | TestimonialStripBlockSelect<T>;
        galleryStrip?: T | GalleryStripBlockSelect<T>;
        awardBadge?: T | AwardBadgeBlockSelect<T>;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  heading?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageTextBlock_select".
 */
export interface ImageTextBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  image?: T;
  imageSide?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "UseCaseTabsBlock_select".
 */
export interface UseCaseTabsBlockSelect<T extends boolean = true> {
  heading?: T;
  tabs?:
    | T
    | {
        label?: T;
        heading?: T;
        body?: T;
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProcessTimelineBlock_select".
 */
export interface ProcessTimelineBlockSelect<T extends boolean = true> {
  heading?: T;
  steps?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsCountersBlock_select".
 */
export interface StatsCountersBlockSelect<T extends boolean = true> {
  heading?: T;
  stats?:
    | T
    | {
        value?: T;
        suffix?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBandBlock_select".
 */
export interface CtaBandBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  buttonLabel?: T;
  buttonHref?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqListBlock_select".
 */
export interface FaqListBlockSelect<T extends boolean = true> {
  heading?: T;
  faqs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialStripBlock_select".
 */
export interface TestimonialStripBlockSelect<T extends boolean = true> {
  heading?: T;
  testimonials?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryStripBlock_select".
 */
export interface GalleryStripBlockSelect<T extends boolean = true> {
  heading?: T;
  category?: T;
  items?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AwardBadgeBlock_select".
 */
export interface AwardBadgeBlockSelect<T extends boolean = true> {
  heading?: T;
  award?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "areas_select".
 */
export interface AreasSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  region?: T;
  isHub?: T;
  heroHeading?: T;
  intro?: T;
  localAngles?:
    | T
    | {
        heading?: T;
        body?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  author?: T;
  platform?: T;
  title?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-items_select".
 */
export interface GalleryItemsSelect<T extends boolean = true> {
  image?: T;
  alt?: T;
  category?: T;
  beforeImage?: T;
  caption?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards_select".
 */
export interface AwardsSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  year?: T;
  image?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quote-requests_select".
 */
export interface QuoteRequestsSelect<T extends boolean = true> {
  type?: T;
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  postcode?: T;
  addressLine1?: T;
  town?: T;
  message?: T;
  propertyType?: T;
  timeline?: T;
  materialPreferences?: T;
  estimator?:
    | T
    | {
        extensionType?: T;
        sizeBand?: T;
        areaM2?: T;
        widthM?: T;
        depthM?: T;
        spec?: T;
        estimateLow?: T;
        estimateHigh?: T;
        surveyRequired?: T;
        surveyFee?: T;
        distanceMiles?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Display format, e.g. 0330 229 0775
   */
  phone?: string | null;
  /**
   * International format without +, e.g. 447845655113
   */
  whatsappNumber?: string | null;
  email?: string | null;
  tagline?: string | null;
  /**
   * Trust line shown near the fold and in the footer.
   */
  awardLine?: string | null;
  socials?: {
    facebook?: string | null;
    instagram?: string | null;
    /**
     * e.g. https://www.tiktok.com/@eazybase2
     */
    tiktok?: string | null;
    yell?: string | null;
    google?: string | null;
  };
  stats?: {
    /**
     * Factory build, weeks
     */
    factoryWeeks?: number | null;
    /**
     * On-site install, days
     */
    installDays?: number | null;
    /**
     * Guarantee, years
     */
    guaranteeYears?: number | null;
  };
  /**
   * The two full-width photo bands on the home page.
   */
  homePhotos?: {
    band1Image?: (number | null) | Media;
    band1Eyebrow?: string | null;
    band1Heading?: string | null;
    band1Sub?: string | null;
    band2Image?: (number | null) | Media;
    band2Eyebrow?: string | null;
    band2Heading?: string | null;
    band2Sub?: string | null;
  };
  /**
   * The 4–6 digit PIN that unlocks the EazyBase Analytics phone app (eazybase-kohl.vercel.app/analytics). Change it any time — it takes effect immediately.
   */
  analyticsPin?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  mainNav?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footerNav?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Controls the /instant-quote estimator. Price = size only; extension type and finish do not change it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quote-pricing".
 */
export interface QuotePricing {
  id: number;
  /**
   * Base price (£) covering up to the floor area below.
   */
  priceFloor?: number | null;
  /**
   * Floor area (m²) included in the base price.
   */
  floorAreaM2?: number | null;
  /**
   * £/m² added to the LOW price for each m² above the floor area.
   */
  startRatePerM2?: number | null;
  /**
   * £/m² flat rate that sets the HIGH price.
   */
  flatRatePerM2?: number | null;
  /**
   * Fee (£) added beyond the radius. Deducted from final cost if they proceed.
   */
  surveyFee?: number | null;
  /**
   * Distance (miles) that triggers the fee.
   */
  surveyDistanceMiles?: number | null;
  /**
   * HQ postcode the distance is measured from.
   */
  basePostcode?: string | null;
  /**
   * Min width (m)
   */
  minWidthM?: number | null;
  /**
   * Max width (m)
   */
  maxWidthM?: number | null;
  /**
   * Min depth (m)
   */
  minDepthM?: number | null;
  /**
   * Max depth (m)
   */
  maxDepthM?: number | null;
  /**
   * Slider step (m).
   */
  stepM?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  phone?: T;
  whatsappNumber?: T;
  email?: T;
  tagline?: T;
  awardLine?: T;
  socials?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        tiktok?: T;
        yell?: T;
        google?: T;
      };
  stats?:
    | T
    | {
        factoryWeeks?: T;
        installDays?: T;
        guaranteeYears?: T;
      };
  homePhotos?:
    | T
    | {
        band1Image?: T;
        band1Eyebrow?: T;
        band1Heading?: T;
        band1Sub?: T;
        band2Image?: T;
        band2Eyebrow?: T;
        band2Heading?: T;
        band2Sub?: T;
      };
  analyticsPin?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  mainNav?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerNav?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quote-pricing_select".
 */
export interface QuotePricingSelect<T extends boolean = true> {
  priceFloor?: T;
  floorAreaM2?: T;
  startRatePerM2?: T;
  flatRatePerM2?: T;
  surveyFee?: T;
  surveyDistanceMiles?: T;
  basePostcode?: T;
  minWidthM?: T;
  maxWidthM?: T;
  minDepthM?: T;
  maxDepthM?: T;
  stepM?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}